---
title: "Incremental full restoration of the 4th order watershed"
output: html_document
date: "2023-06-27"
---

#Housekeeping:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(tidyverse)
library(stringr)
library(tidyr)
library(readr)

theme_set(theme_classic())

#removal rates in mg-N/ft2.hr. Converted to g in the removal calc below.
k10 <- 0.0067
km <- 0.061
k90 <- 1.3
Xcs <- 50 #Distance between cross sections (ft)
```

#Full Watershed Restoration in 20% Increments Calculations:
##Read in data from text files:
```{r}
#Make vector of file names, then convert to DF and include the location to use later to read in the files.
raw.files <- tibble(filename = list.files("TextFilesFull/"))
raw.file.paths <- raw.files  %>%
  mutate(filepath = paste0("TextFilesFull/", filename))


#Read in and combine files into one df (~ 1.5 hrs on DELL)
RAS_Full <- NULL
for (f in raw.file.paths$filepath) {
  dat <- read_fwf(f, 
                  skip = 12, 
                  fwf_widths(c(10, 20, 15, 4, 9),
                    col_names = c("reach", "STA", "day", "time", "wettedFPw")), 
                    col_types = cols(reach = "c", STA = "c", day = "c", time = "c", wettedFPw = "n")) %>%
         mutate(plan = f)
   RAS_Full <- bind_rows(RAS_Full, dat)
}

#Editing (Cant run separate wider or the sub string arguments multiple times. It will keep altering beyond the desired outcome)
RAS_Full <- RAS_Full %>%
  drop_na(STA) %>%
  mutate(STA = 
           case_when(
             endsWith(STA, ".*") ~ substr(STA, 1, nchar(STA)-2),
             endsWith(STA, ".0*") ~ substr(STA, 1, nchar(STA)-3),
             endsWith(STA, ".00*") ~ substr(STA, 1, nchar(STA)-4),
             TRUE ~ STA) ) %>%
  separate_wider_delim(plan, 
                       delim = "_", names = c("river", "storm", "plan")) %>%
  mutate(river = 
           substring(river,
                     first = 15,
                     last = 17), 
         plan = 
           case_when(river == "3-1" | river == "4-1" 
                                  ~ substr(plan, 1, nchar(plan)-6), 
                     TRUE 
                                  ~ substr(plan, 1, nchar(plan)-4))) 

RAS_Full$STA <- as.numeric(RAS_Full$STA) #Convert to numeric. STA needed to be a character to remove the * from hecras, but it is needed as a number for calculations.

rm(dat, raw.file.paths, raw.files) #remove clutter from environment. These dataframes hold no purpose anymore.

#To save data frames in the environment
# save(RAS_Full,
#      file = "C:/Users/morganao/Documents/CBT_Oehler2023/12_Saved_Dataframes/Full_RAS_rawData.RData")

# save(NO3_Full,
#      file = "C:/Users/morganao/Documents/CBT_Oehler2023/12_Saved_Dataframes/Full_InunTimes.RData")

# Test <- NO3_Full %>%
#   filter(storm == "Q1" & plan == "1st-20p" & river == "3-1" )
#  
# NO3_1stO%>%
#   filter(storm == "Q1" & plan == "1st-20p" & river == "3-1" )
# 
# read_fwf("TextFilesFull/3-1_Q1_1st-20p.1.txt", 
#                   skip = 12, 
#                   fwf_widths(c(10, 20, 15, 4, 9),
#                     col_names = c("reach", "STA", "day", "time", "wettedFPw")), 
#                     col_types = cols(reach = "c", STA = "c", day = "c", time = "c", wettedFPw = "n"))
```


#%NO3 Removal by Cumulative Restoration of the entire watershed. 
```{r}
#Nitrate loads for 1mg/L source concentration(g)
Q2_watershed_load <- 4563108 #total NO3 load to the watershed (grams)
Q2_load1 <- 141902 #input load to a all first order streams (grams)
Q2_load2 <- 120581 #input load to a all second order streams (grams)
Q2_load3 <- 680432 #input load to a all third order streams (grams)
Q2_load4 <- 3620193 #input load to the fourth order stream (grams)

Q1_watershed_load <- 3653361 #total NO3 load to the watershed (grams)
Q1_load1 <- 102974 #input load to a all first order streams (grams)
Q1_load2 <- 126125 #input load to a all second order streams (grams)
Q1_load3 <- 545822 #input load to a all third order streams (grams)
Q1_load4 <- 2878440 #input load to the fourth order stream (grams)

Q0.5_watershed_load <- 2262609 #total NO3 load to the watershed (grams)
Q0.5_load1 <- 91515 #input load to a all first order streams (grams)
Q0.5_load2 <- 74539 #input load to a all second order streams (grams)
Q0.5_load3 <- 325804 #input load to a all third order streams (grams)
Q0.5_load4 <- 1770751 #input load to the fourth order stream (grams)

Qm_watershed_load <- 245161 #total NO3 load to the watershed (grams)
Qm_load1 <- 65880 #input load to a all first order streams (grams)
Qm_load2 <- 3003 #input load to a all second order streams (grams)
Qm_load3 <- 26865 #input load to a all third order streams (grams)
Qm_load4 <- 149414 #input load to the fourth order stream (grams)
  
NO3_Full <- RAS_Full %>%
  group_by(storm, plan, STA, river) %>%
  mutate(
    ti_min = case_when(wettedFPw >= 15 ~ 15)) %>%
  summarise(
    ti_tot_min = sum(ti_min, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(
    FP_width = 
           case_when(
             plan == "unr" & river == "1-7" ~ 16.5, 
             plan == "unr" & river == "2-2" ~ 34.5,
             plan == "unr" & river == "3-1" ~ 67.5,
             plan == "unr" & river == "4-1" ~ 126,
             
             plan == "1st-20p" & river == "1-7" & STA >= 164300 ~ 60,
             plan == "1st-20p" & river == "1-7" & STA < 164300 ~ 16.5,
             plan == "1st-20p" & river == "2-2" ~ 34.5,
             plan == "1st-20p" & river == "3-1" ~ 67.5,
             plan == "1st-20p" & river == "4-1" ~ 126,
             
             plan == "1st-40p" & river == "1-7" & STA >= 163100 ~ 60,
             plan == "1st-40p" & river == "1-7" & STA < 163100 ~ 16.5,
             plan == "1st-40p" & river == "2-2" ~ 34.5,
             plan == "1st-40p" & river == "3-1" ~ 67.5,
             plan == "1st-40p" & river == "4-1" ~ 126,
             
             plan == "1st-60p" & river == "1-7" & STA >= 161900 ~ 60,
             plan == "1st-60p" & river == "1-7" & STA < 161900 ~ 16.5,
             plan == "1st-60p" & river == "2-2" ~ 34.5,
             plan == "1st-60p" & river == "3-1" ~ 67.5,
             plan == "1st-60p" & river == "4-1" ~ 126,
             
             plan == "1st-80p" & river == "1-7" & STA >= 160700 ~ 60,
             plan == "1st-80p" & river == "1-7" & STA < 160700 ~ 16.5,
             plan == "1st-80p" & river == "2-2" ~ 34.5,
             plan == "1st-80p" & river == "3-1" ~ 67.5,
             plan == "1st-80p" & river == "4-1" ~ 126,
             
             plan == "1st-100p" & river == "1-7" ~ 60,
             plan == "1st-100p" & river == "2-2" ~ 34.5,
             plan == "1st-100p" & river == "3-1" ~ 67.5,
             plan == "1st-100p" & river == "4-1" ~ 126,
             
             plan == "full-2nd-20p" & river == "1-7" ~ 60,
             plan == "full-2nd-20p" & river == "2-2" & STA >= 156200 ~ 65,
             plan == "full-2nd-20p" & river == "2-2" & STA < 156200 ~ 34.5,
             plan == "full-2nd-20p" & river == "3-1" ~ 67.5,
             plan == "full-2nd-20p" & river == "4-1" ~ 126,
             
             plan == "full-2nd-60p" & river == "1-7" ~ 60,
             plan == "full-2nd-60p" & river == "2-2" & STA >= 149600 ~ 65,
             plan == "full-2nd-60p" & river == "2-2" & STA < 149600 ~ 34.5,
             plan == "full-2nd-60p" & river == "3-1" ~ 67.5,
             plan == "full-2nd-60p" & river == "4-1" ~ 126,
             
             plan == "full-2nd-80p" & river == "1-7" ~ 60,
             plan == "full-2nd-80p" & river == "2-2" & STA >= 146300 ~ 65,
             plan == "full-2nd-80p" & river == "2-2" & STA < 146300 ~ 34.5,
             plan == "full-2nd-80p" & river == "3-1" ~ 67.5,
             plan == "full-2nd-80p" & river == "4-1" ~ 126,

             plan == "full-2nd-100p" & river == "1-7" ~ 60,
             plan == "full-2nd-100p" & river == "2-2" ~ 65,
             plan == "full-2nd-100p" & river == "3-1" ~ 67.5,
             plan == "full-2nd-100p" & river == "4-1" ~ 126,
             
             plan == "full-3rd-20p" & river == "1-7" ~ 60,
             plan == "full-3rd-20p" & river == "2-2" ~ 65,
             plan == "full-3rd-20p" & river == "3-1" & STA >= 134600 ~ 75,
             plan == "full-3rd-20p" & river == "3-1" & STA < 134600 ~ 67.5,
             plan == "full-3rd-20p" & river == "4-1" ~ 126,
             
             plan == "full-3rd-40p" & river == "1-7" ~ 60,
             plan == "full-3rd-40p" & river == "2-2" ~ 65,
             plan == "full-3rd-40p" & river == "3-1" & STA >= 126200 ~ 75,
             plan == "full-3rd-40p" & river == "3-1" & STA < 126200 ~ 67.5,
             plan == "full-3rd-40p" & river == "4-1" ~ 126,
             
             plan == "full-3rd-60p" & river == "1-7" ~ 60,
             plan == "full-3rd-60p" & river == "2-2" ~ 65,
             plan == "full-3rd-60p" & river == "3-1" & STA >= 117800 ~ 75,
             plan == "full-3rd-60p" & river == "3-1" & STA < 117800 ~ 67.5,
             plan == "full-3rd-60p" & river == "4-1" ~ 126,
             
             plan == "full-3rd-80p" & river == "1-7" ~ 60,
             plan == "full-3rd-80p" & river == "2-2" ~ 65,
             plan == "full-3rd-80p" & river == "3-1" & STA >= 109400 ~ 75,
             plan == "full-3rd-80p" & river == "3-1" & STA < 109400 ~ 67.5,
             plan == "full-3rd-80p" & river == "4-1" ~ 126,
             
             plan == "full-3rd-100p" & river == "1-7" ~ 60,
             plan == "full-3rd-100p" & river == "2-2" ~ 65,
             plan == "full-3rd-100p" & river == "3-1" ~ 75,
             plan == "full-3rd-100p" & river == "4-1" ~ 126,
             
             plan == "full-4th-20p" & river == "1-7" ~ 60,
             plan == "full-4th-20p" & river == "2-2" ~ 65,
             plan == "full-4th-20p" & river == "3-1" ~ 75,
             plan == "full-4th-20p" & river == "4-1" & STA >= 80800 ~ 130,
             plan == "full-4th-20p" & river == "4-1" & STA < 80800 ~ 126,
             
             plan == "full-4th-40p" & river == "1-7" ~ 60,
             plan == "full-4th-40p" & river == "2-2" ~ 65,
             plan == "full-4th-40p" & river == "3-1" ~ 75,
             plan == "full-4th-40p" & river == "4-1" & STA >= 60600 ~ 130,
             plan == "full-4th-40p" & river == "4-1" & STA < 60600 ~ 126,
             
             plan == "full-4th-60p" & river == "1-7" ~ 60,
             plan == "full-4th-60p" & river == "2-2" ~ 65,
             plan == "full-4th-60p" & river == "3-1" ~ 75,
             plan == "full-4th-60p" & river == "4-1" & STA >= 40400 ~ 130,
             plan == "full-4th-60p" & river == "4-1" & STA < 40400 ~ 126,
             
             plan == "full-4th-80p" & river == "1-7" ~ 60,
             plan == "full-4th-80p" & river == "2-2" ~ 65,
             plan == "full-4th-80p" & river == "3-1" ~ 75,
             plan == "full-4th-80p" & river == "4-1" & STA >= 20200 ~ 130,
             plan == "full-4th-80p" & river == "4-1" & STA < 20200 ~ 126,
             
             plan == "full-4th-100p" & river == "1-7" ~ 60,
             plan == "full-4th-100p" & river == "2-2" ~ 65,
             plan == "full-4th-100p" & river == "3-1" ~ 75,
             plan == "full-4th-100p" & river == "4-1" ~ 130)) %>%
  mutate(
    k10_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                    ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                    ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
                          
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                    ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
          
                river == "4-1" & (STA < 101000)
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000)) %>% 
   mutate(
    km_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000)) %>% 
  mutate(
    k90_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000)) %>% 
  group_by(storm, plan, river) %>%
  summarise(removal_k10_g = sum(k10_removal_g),
            removal_km_g = sum(km_removal_g),
            removal_k90_g = sum(k90_removal_g)) %>%
  mutate(removal_k10_g = case_when(river == "1-7" ~ removal_k10_g*24, 
                                 river == "2-2" ~ removal_k10_g*6,
                                 river == "3-1" ~ removal_k10_g*2,
                                 river == "4-1" ~ removal_k10_g),
         removal_km_g = case_when(river == "1-7" ~ removal_km_g*24, 
                                 river == "2-2" ~ removal_km_g*6,
                                 river == "3-1" ~ removal_km_g*2,
                                 river == "4-1" ~ removal_km_g),
         removal_k90_g = case_when(river == "1-7" ~ removal_k90_g*24, 
                                 river == "2-2" ~ removal_k90_g*6,
                                 river == "3-1" ~ removal_k90_g*2,
                                 river == "4-1" ~ removal_k90_g)) %>%
  mutate(order = 
           case_when(            river == "1-7" ~ "1st", 
                                 river == "2-2" ~ "2nd",
                                 river == "3-1" ~ "3rd",
                                 river == "4-1" ~ "4th")) %>% 
  mutate(PerShedRest = case_when(plan == "unr" ~ 0,
                                 plan == "1st-20p" ~ 7, 
                                 plan == "1st-40p" ~ 13,
                                 plan == "1st-60p" ~ 20,
                                 plan == "1st-80p" ~ 27,
                                 plan == "1st-100p" ~ 34,
                                 plan == "full-2nd-20p" ~ 38,
                                 plan == "full-2nd-60p" ~ 48,
                                 plan == "full-2nd-80p" ~ 52,
                                 plan == "full-2nd-100p" ~ 57,
                                 plan == "full-3rd-20p" ~ 61,
                                 plan == "full-3rd-40p" ~ 65,
                                 plan == "full-3rd-60p" ~ 69,
                                 plan == "full-3rd-80p" ~ 72,
                                 plan == "full-3rd-100p" ~ 76,
                                 plan == "full-4th-20p" ~ 81,
                                 plan == "full-4th-40p" ~ 86,
                                 plan == "full-4th-60p" ~ 91,
                                 plan == "full-4th-80p" ~ 95,
                                 plan == "full-4th-100p" ~ 100)) %>%
  mutate(k10_percentWLR = case_when(storm == "Q2" ~
                                   (removal_k10_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k10_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k10_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k10_g/Qm_watershed_load)*100),
         km_percentWLR = case_when(storm == "Q2" ~
                                   (removal_km_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_km_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_km_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_km_g/Qm_watershed_load)*100),
         k90_percentWLR = case_when(storm == "Q2" ~
                                   (removal_k90_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k90_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k90_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k90_g/Qm_watershed_load)*100)) %>%
  mutate(k10_percentOLR = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k10_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k10_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k10_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k10_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k10_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k10_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k10_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k10_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k10_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k10_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k10_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k10_g/Qm_load4)*100),
         km_percentOLR = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_km_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_km_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_km_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_km_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_km_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_km_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_km_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_km_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_km_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_km_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_km_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_km_g/Qm_load4)*100),
         k90_percentOLR = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k90_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k90_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k90_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k90_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k90_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k90_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k90_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k90_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k90_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k90_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k90_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k90_g/Qm_load4)*100))


#Nitrate loads for 2mg/L source concentration(g)
Q2_watershed_load <- 9126217 #total NO3 load to the watershed (grams)
Q2_load1 <- 283805 #input load to a all first order streams (grams)
Q2_load2 <- 241163 #input load to a all second order streams (grams)
Q2_load3 <- 1360864 #input load to a all third order streams (grams)
Q2_load4 <- 7240386 #input load to the fourth order stream (grams)

Q1_watershed_load <- 7306722 #total NO3 load to the watershed (grams)
Q1_load1 <- 205948 #input load to a all first order streams (grams)
Q1_load2 <- 252249 #input load to a all second order streams (grams)
Q1_load3 <- 1091643 #input load to a all third order streams (grams)
Q1_load4 <- 5756881 #input load to the fourth order stream (grams)

Q0.5_watershed_load <- 4525219 #total NO3 load to the watershed (grams)
Q0.5_load1 <- 183030 #input load to a all first order streams (grams)
Q0.5_load2 <- 149078 #input load to a all second order streams (grams)
Q0.5_load3 <- 651608 #input load to a all third order streams (grams)
Q0.5_load4 <- 3541503 #input load to the fourth order stream (grams)

Qm_watershed_load <- 490322 #total NO3 load to the watershed (grams)
Qm_load1 <- 131760 #input load to a all first order streams (grams)
Qm_load2 <- 6005 #input load to a all second order streams (grams)
Qm_load3 <- 53730 #input load to a all third order streams (grams)
Qm_load4 <- 298827 #input load to the fourth order stream (grams)

NO3_Full <- NO3_Full %>%
  mutate(k10_pWLR_2mgL = case_when(storm == "Q2" ~
                                   (removal_k10_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k10_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k10_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k10_g/Qm_watershed_load)*100),
         km_pWLR_2mgL = case_when(storm == "Q2" ~
                                   (removal_km_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_km_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_km_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_km_g/Qm_watershed_load)*100),
         k90_pWLR_2mgL = case_when(storm == "Q2" ~
                                   (removal_k90_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k90_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k90_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k90_g/Qm_watershed_load)*100)) %>%
  mutate(k10_pOLR_2mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k10_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k10_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k10_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k10_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k10_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k10_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k10_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k10_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k10_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k10_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k10_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k10_g/Qm_load4)*100),
         km_pOLR_2mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_km_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_km_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_km_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_km_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_km_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_km_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_km_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_km_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_km_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_km_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_km_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_km_g/Qm_load4)*100),
         k90_pOLR_2mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k90_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k90_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k90_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k90_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k90_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k90_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k90_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k90_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k90_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k90_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k90_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k90_g/Qm_load4)*100))

#Nitrate loads for 0.5mg/L source concentration(g)
Q2_watershed_load <- 2281554 #total NO3 load to the watershed (grams)
Q2_load1 <- 70951 #input load to a all first order streams (grams)
Q2_load2 <- 60291 #input load to a all second order streams (grams)
Q2_load3 <- 340216 #input load to a all third order streams (grams)
Q2_load4 <- 1810096 #input load to the fourth order stream (grams)

Q1_watershed_load <- 1826680 #total NO3 load to the watershed (grams)
Q1_load1 <- 51487 #input load to a all first order streams (grams)
Q1_load2 <- 63062 #input load to a all second order streams (grams)
Q1_load3 <- 272911 #input load to a all third order streams (grams)
Q1_load4 <- 1439220 #input load to the fourth order stream (grams)

Q0.5_watershed_load <- 1131305 #total NO3 load to the watershed (grams)
Q0.5_load1 <- 45757 #input load to a all first order streams (grams)
Q0.5_load2 <- 37270 #input load to a all second order streams (grams)
Q0.5_load3 <- 162902 #input load to a all third order streams (grams)
Q0.5_load4 <- 885376 #input load to the fourth order stream (grams)

Qm_watershed_load <- 122581 #total NO3 load to the watershed (grams)
Qm_load1 <- 32940 #input load to a all first order streams (grams)
Qm_load2 <- 1501 #input load to a all second order streams (grams)
Qm_load3 <- 13432 #input load to a all third order streams (grams)
Qm_load4 <- 74707 #input load to the fourth order stream (grams)

NO3_Full <- NO3_Full %>%
  mutate(k10_pWLR_.5mgL = case_when(storm == "Q2" ~
                                   (removal_k10_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k10_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k10_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k10_g/Qm_watershed_load)*100),
         km_pWLR_.5mgL = case_when(storm == "Q2" ~
                                   (removal_km_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_km_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_km_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_km_g/Qm_watershed_load)*100),
         k90_pWLR_.5mgL = case_when(storm == "Q2" ~
                                   (removal_k90_g/Q2_watershed_load)*100,
                                   storm == "Q1" ~
                                   (removal_k90_g/Q1_watershed_load)*100,
                                   storm == "Q0.5" ~
                                   (removal_k90_g/Q0.5_watershed_load)*100,
                                   storm == "Qm" ~
                                   (removal_k90_g/Qm_watershed_load)*100)) %>%
  mutate(k10_pOLR_.5mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k10_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k10_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k10_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k10_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k10_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k10_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k10_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k10_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k10_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k10_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k10_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k10_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k10_g/Qm_load4)*100),
         km_pOLR_.5mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_km_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_km_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_km_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_km_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_km_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_km_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_km_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_km_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_km_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_km_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_km_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_km_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_km_g/Qm_load4)*100),
         k90_pOLR_.5mgL = 
           case_when(river == "1-7" & storm == "Q2" ~ (removal_k90_g/Q2_load1)*100,
                     river == "1-7" & storm == "Q1" ~ (removal_k90_g/Q1_load1)*100,
                     river == "1-7" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load1)*100,
                     river == "1-7" & storm == "Qm" ~ (removal_k90_g/Qm_load1)*100,
                     river == "2-2" & storm == "Q2" ~ (removal_k90_g/Q2_load2)*100,
                     river == "2-2" & storm == "Q1" ~ (removal_k90_g/Q1_load2)*100,
                     river == "2-2" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load2)*100,
                     river == "2-2" & storm == "Qm" ~ (removal_k90_g/Qm_load2)*100,
                     river == "3-1" & storm == "Q2" ~ (removal_k90_g/Q2_load3)*100,
                     river == "3-1" & storm == "Q1" ~ (removal_k90_g/Q1_load3)*100,
                     river == "3-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load3)*100,
                     river == "3-1" & storm == "Qm" ~ (removal_k90_g/Qm_load3)*100,
                     river == "4-1" & storm == "Q2" ~ (removal_k90_g/Q2_load4)*100,
                     river == "4-1" & storm == "Q1" ~ (removal_k90_g/Q1_load4)*100,
                     river == "4-1" & storm == "Q0.5" ~ (removal_k90_g/Q0.5_load4)*100,
                     river == "4-1" & storm == "Qm" ~ (removal_k90_g/Qm_load4)*100))

  
```


