---
title: "Inundation Time Analysis"
output: html_document
date: "2023-08-07"
---
#Housekeeping
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(stringr)
library(tidyr)

library(readr)
library(patchwork)
theme_set(theme_classic())

```

#Removal load vs inundation time
```{r}
#calculate loads at each cross section. Combine dfs for 1st, 2nd, 3rd, and 4th order restoration scenarios.Only including the median rate.

inunVSrem1 <- inun_1stO %>%
  filter(ti_tot_min > 0) %>% #cut down DF size by excluding DFs with no FP inundation
  mutate(
    FP_width = 
           case_when(
             plan == "unr" & river == "1-7" ~ 16.5, 
             plan == "1st-20p" & river == "1-7" & STA >= 164300 ~ 60,
             plan == "1st-20p" & river == "1-7" & STA < 164300 ~ 16.5,
             plan == "1st-40p" & river == "1-7" & STA >= 163100 ~ 60,
             plan == "1st-40p" & river == "1-7" & STA < 163100 ~ 16.5,
             plan == "1st-60p" & river == "1-7" & STA >= 161900 ~ 60,
             plan == "1st-60p" & river == "1-7" & STA < 161900 ~ 16.5,
             plan == "1st-80p" & river == "1-7" & STA >= 160700 ~ 60,
             plan == "1st-80p" & river == "1-7" & STA < 160700 ~ 16.5,
             plan == "1st-100p" & river == "1-7" ~ 60,
             river == "2-2" ~ 34.5,
             river == "3-1" ~ 67.5,
             river == "4-1" ~ 126)) %>% 
   mutate(
    km_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000))%>%
   mutate(removal_scaled_g = case_when(river == "1-7" ~ km_removal_g*24, #scales removal to the number of rivers in the order
                                       river == "2-2" ~ km_removal_g*6,
                                       river == "3-1" ~ km_removal_g*2,
                                       river == "4-1" ~ km_removal_g))
  
inunVSrem2 <- inun_2ndO %>%
  filter(ti_tot_min > 0)%>%
  mutate(
    FP_width = 
           case_when(
             river == "1-7" ~ 16.5,
             plan == "unr" & river == "2-2" ~ 34.5, 
             plan == "2nd-20p" & river == "2-2" & STA >= 156200 ~ 65,
             plan == "2nd-20p" & river == "2-2" & STA < 156200 ~ 34.5,
             plan == "2nd-60p" & river == "2-2" & STA >= 149600 ~ 65,
             plan == "2nd-60p" & river == "2-2" & STA < 149600 ~ 34.5,
             plan == "2nd-80p" & river == "2-2" & STA >= 146300 ~ 65,
             plan == "2nd-80p" & river == "2-2" & STA < 146300 ~ 34.5,
             plan == "2nd-100p" & river == "2-2" ~ 65,
             river == "3-1" ~ 67.5,
             river == "4-1" ~ 126)) %>% 
   mutate(
    km_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000)) %>%
  mutate(removal_scaled_g = case_when(river == "1-7" ~  km_removal_g*24, #scales removal to the number of rivers in the order
                                       river == "2-2" ~ km_removal_g*6,
                                       river == "3-1" ~ km_removal_g*2,
                                       river == "4-1" ~ km_removal_g))

inunVSrem3 <- inun_3rdO %>%
  filter(ti_tot_min > 0)%>%
  mutate(
    FP_width = 
           case_when(
             river == "1-7" ~ 16.5,
             river == "2-2" ~ 34.5,
             plan == "unr" & river == "3-1" ~ 67.5, 
             plan == "3rd-20p" & river == "3-1" & STA >= 134600 ~ 75,
             plan == "3rd-20p" & river == "3-1" & STA < 134600 ~ 67.5,
             plan == "3rd-40p" & river == "3-1" & STA >= 126200 ~ 75,
             plan == "3rd-40p" & river == "3-1" & STA < 126200 ~ 67.5,
             plan == "3rd-60p" & river == "3-1" & STA >= 117800 ~ 75,
             plan == "3rd-60p" & river == "3-1" & STA < 117800 ~ 67.5,
             plan == "3rd-80p" & river == "3-1" & STA >= 109400 ~ 75,
             plan == "3rd-80p" & river == "3-1" & STA < 109400 ~ 67.5,
             plan == "3rd-100p" & river == "3-1" ~ 75,
             river == "4-1" ~ 126)) %>% 
  mutate(
    km_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000)) %>%
  mutate(removal_scaled_g = case_when(river == "1-7" ~  km_removal_g*24, #scales removal to the number of rivers in the order
                                       river == "2-2" ~ km_removal_g*6,
                                       river == "3-1" ~ km_removal_g*2,
                                       river == "4-1" ~ km_removal_g))
  
inunVSrem4 <- inun_4thO %>%
  filter(ti_tot_min > 0)%>%
  mutate(
    FP_width = 
           case_when(
             river == "1-7" ~ 16.5, 
             river == "2-2" ~ 34.5,
             river == "3-1" ~ 67.5,
             plan == "unr" & river == "4-1" ~ 126, 
             plan == "4th-20p" & river == "4-1" & STA >= 80800 ~ 130,
             plan == "4th-20p" & river == "4-1" & STA < 80800 ~ 126,
             plan == "4th-40p" & river == "4-1" & STA >= 60600 ~ 130,
             plan == "4th-40p" & river == "4-1" & STA < 60600 ~ 126,
             plan == "4th-60p" & river == "4-1" & STA >= 40400 ~ 130,
             plan == "4th-60p" & river == "4-1" & STA < 40400 ~ 126,
             plan == "4th-80p" & river == "4-1" & STA >= 20200 ~ 130,
             plan == "4th-80p" & river == "4-1" & STA < 20200 ~ 126,
             plan == "4th-100p" & river == "4-1" ~ 130)) %>% 
  mutate(
    km_removal_g = 
      case_when(river == "1-7" & STA %in% c(165500,159500) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "1-7" & STA < 165500 & STA > 159500 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                            
                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "2-2" & (STA < 159500 & STA > 154000) | 
                                 (STA < 154000 & STA > 148500) | 
                                 (STA < 148500 & STA > 143000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "3-1" & (STA < 143000 & STA > 122000) | 
                                 (STA < 122000 & STA > 101000) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,
                          
                river == "4-1" & STA %in% c(101000, 0) 
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000, 
                river == "4-1" & (STA < 101000 & STA > 0) 
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000)) %>% 
  mutate(removal_scaled_g = case_when(river == "1-7" ~  km_removal_g*24, #scales removal to the number of rivers in the order
                                       river == "2-2" ~ km_removal_g*6,
                                       river == "3-1" ~ km_removal_g*2,
                                       river == "4-1" ~ km_removal_g))
  
inunVSrem <- bind_rows(inunVSrem1, inunVSrem2, inunVSrem3, inunVSrem4)%>%
  group_by(storm, plan, river)%>%
  summarize(ti_avg_hr = sum(ti_tot_min)/60,
            removal_scaled_kg = sum(removal_scaled_g)/1000) %>% 
  mutate(order = 
           case_when(river == "1-7" ~ "1st-order rivers",
                     river == "2-2" ~ "2nd-order rivers",
                     river == "3-1" ~ "3rd-order rivers",
                     river == "4-1" ~ "4th-order river"))%>%
  mutate(restLoc = 
           case_when(startsWith(plan, "unr") ~ "unr",
                     startsWith(plan, "1st") ~ "1st",
                     startsWith(plan, "2nd") ~ "2nd",
                     startsWith(plan, "3rd") ~ "3rd",
                     startsWith(plan, "4th") ~ "4th"))
  
inunVSrem$storm <- factor(inunVSrem$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

inunVSrem %>%
  # filter(plan == "unr")%>%
  filter(order ==  "1st-order rivers" | order ==  "2nd-order rivers")%>%
  # filter(order ==  "3rd-order rivers" | order ==  "4th-order river")%>%
  ggplot()+
  geom_point(aes(ti_avg_hr, removal_scaled_kg, color = storm, shape = order))+
  # xlim(0,20)+
  # ylim(0,30)+
  xlab("Average Inundation time (hrs)")+
  # scale_x_log10()+
  ylab(expression("NO"[3]*" Load Removed (kg)"))+
  labs(color = "Storm", shape = "Inundation Location")+
  ggtitle(expression(atop("Inundation Time vs Nitrate Load Removed (k"[m]*" rate)")))+
  plot_annotation(theme = theme(title = element_text(size = 12, face = 2))) &
  theme(text = element_text(size = 10))

# ggsave("Figures/timeAVGvsremoval_km.png", dpi=500, width = 7, height = 4, units="in")

```

#Total inundation time Matrix
```{r plot-wider, fig.width=16, fig.height=4}
first <- filter_inun1stO %>%
  filter(river =="1-7")%>%
  ggplot()+
  geom_line(aes(x = percentRest, y = max_ti_hr, color = storm))+
  geom_point(aes(x = percentRest, y = max_ti_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  ylab(expression(atop("Total Floodplain Inundation Time (days)")))+
  xlab(expression(atop("Percent 1"^st*"-order streams restored")))+
  # theme(aspect.ratio = 1)+
  ggtitle(expression(atop("1"^st*"-order River")))

second <- filter_inun2ndO %>%
  filter(river =="2-2")%>%
  ggplot()+
  geom_line(aes(x = percentRest, y = max_ti_hr, color = storm))+
  geom_point(aes(x = percentRest, y = max_ti_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  ylab(element_blank())+
  xlab(expression(atop("Percent 2"^nd*"-order streams restored")))+
  # theme(aspect.ratio = 1)+
  # ylim(0,1000)+
  ggtitle(expression(atop("2"^nd*"-order River")))

third <- filter_inun3rdO %>%
  filter(river =="3-1")%>%
  ggplot()+
  geom_line(aes(x = percentRest, y = max_ti_hr, color = storm))+
  geom_point(aes(x = percentRest, y = max_ti_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  ylab(element_blank())+
  xlab(expression(atop("Percent 3"^rd*"-order streams restored")))+
  # theme(aspect.ratio = 1)+
  # ylim(0,8000)+
  ggtitle(expression(atop("3"^rd*"-order River")))

fourth <- filter_inun4thO %>%
  filter(river == "4-1")%>%
  ggplot()+
  geom_line(aes(x = percentRest, y = max_ti_hr, color = storm))+
  geom_point(aes(x = percentRest, y = max_ti_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  ylab(element_blank())+
  xlab(expression(atop("Percent 4"^th*"-order streams restored")))+
  # theme(aspect.ratio = 1)+
  # ylim(0,40000)+
  ggtitle(expression(atop("4"^th*"-order River")))

first+second+third+fourth +
   plot_layout(ncol = 4, guides = "collect")+
             plot_annotation(title = expression(atop('Total Inundation Time In a Single River Due to Restoration in the River')),
                             tag_levels = 'A',
                             theme = theme(title = element_text(size = 12, face = 2))) &
  theme(text = element_text(size = 10))
ggsave("Figures/totInun_diagonal.png", dpi=500, height = 4, width = 16,  units="in")
```

```{r}
#dont think need a matrix for this right now
# #1
# one <- filter_inun1stO %>%
#   filter(storm == "Q2") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab("Total Floodplain Inundation Time \n in a 1st-order River")+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,60)+
#         theme(aspect.ratio = 1)
# #5
# five <- filter_inun1stO %>%
#   filter(storm == "Q1") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab("Total Floodplain Inundation Time \n in a 2nd-order River")+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1000)+
#         theme(aspect.ratio = 1)
# #9
# nine <- filter_inun1stO %>%
#   filter(storm == "Q0.5") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab("Total Floodplain Inundation Time \n in a 3rd-order River")+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# #13
# thirteen <- filter_inun1stO %>%
#   filter(storm == "Qm") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab("Percent 1st-order Stream Restored")+
#   ylab("Total Floodplain Inundation Time \n in a 4th-order River")+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# 
# #2
# two <- filter_inun2ndO %>%
#   filter(storm == "Q2") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20),  sec.axis = sec_axis(~. * 0.30175, name = "Total Length of 2nd-order Rivers Restored [km]", breaks = seq(0,35,5)))+
#   # ylim(0,60)+
#         theme(aspect.ratio = 1)
# #6
# six <- filter_inun2ndO %>%
#   filter(storm == "Q1") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1000)+
#         theme(aspect.ratio = 1)
# #10
# ten <- filter_inun2ndO %>%
#   filter(storm == "Q0.5") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# #14
# fourteen <- filter_inun2ndO %>%
#   filter(storm == "Qm") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab("Percent of 2nd-order\n Streams Restored")+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# 
# #3
# three <- filter_inun3rdO %>%
#   filter(storm == "Q2") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,60)+
#         theme(aspect.ratio = 1)
# #7
# seven <- filter_inun3rdO %>%
#   filter(storm == "Q1") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1000)+
#         theme(aspect.ratio = 1)
# #11
# eleven <- filter_inun3rdO %>%
#   filter(storm == "Q0.5") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#  # ylim(0,1)+
#         theme(aspect.ratio = 1)
# #15
# fifteen <- filter_inun3rdO %>%
#   filter(storm == "Qm") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab("Percent of 3rd-order\n Streams Restored")+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# 
# #4
# four <- filter_inun4thO %>%
#   filter(storm == "Q2") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,60)+
#         theme(aspect.ratio = 1)
# #8
# eight <- filter_inun4thO %>%
#   filter(storm == "Q1") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   # ylim(0,1000)+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#         theme(aspect.ratio = 1)
# #12
# twelve <- filter_inun4thO %>%
#   filter(storm == "Q0.5") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab(element_blank())+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# #16
# sixteen <- filter_inun4thO %>%
#   filter(storm == "Qm") %>%
#   ggplot() +
#   geom_line(aes(x = percentRest, y = ti_min, color = river), linewidth = 0.5)+
#   geom_point(aes(x = percentRest, y = ti_min, color = river), size = 0.2)+
#   xlab("Percent of 4th-order \n Streams Restored")+
#   ylab(element_blank())+
#   scale_x_continuous(breaks=seq(0,100,by=20))+
#   # ylim(0,1)+
#         theme(aspect.ratio = 1)
# 
# 
# one+theme(text = element_text(size = 6))+scale_x_continuous(sec.axis = sec_axis(~. * 0.43891, name = "Total Length of 1st-order Rivers Restored [km]", breaks = seq(0,50,10)))+
# two+theme(text = element_text(size = 6))+scale_x_continuous(sec.axis = sec_axis(~. * 0.30175, name = "Total Length of 2nd-order Rivers Restored [km]", breaks = seq(0,35,5)))+
# three+theme(text = element_text(size = 6))+scale_x_continuous(sec.axis = sec_axis(~. * 0.25603, name = "Total Length of 3rd-order Rivers Restored [km]", breaks = seq(0,30,5)))+
# four+theme(text = element_text(size = 6))+ scale_x_continuous(sec.axis = sec_axis(~. * 0.30785, name = "Total Length of 4th-order River Restored [km]", breaks = seq(0,35,5)))+
# five+theme(text = element_text(size = 6))+
# six+theme(text = element_text(size = 6))+
# seven+theme(text = element_text(size = 6))+
# eight+theme(text = element_text(size = 6))+
# nine+theme(text = element_text(size = 6))+
# ten+theme(text = element_text(size = 6))+
# eleven +theme(text = element_text(size = 6))+ 
# twelve +theme(text = element_text(size = 6))+ 
# thirteen+theme(text = element_text(size = 6))+
# fourteen+theme(text = element_text(size = 6))+
# fifteen+theme(text = element_text(size = 6))+
# sixteen+theme(text = element_text(size = 6))+
#             plot_layout(ncol = 4, guides = "collect")+
#             plot_annotation(title = 'Percent NO3 Removed from the Watershed Cumulatively (km)', 
#                             theme = theme(title = element_text(size = 8, face = 2)))
```

##Average inundation time DFs & plots:
```{r plot-wider, fig.width=16, fig.height=4}
#calculating average inundation times in single rivers of different orders. Does not include XS that are never inundated.
avg_inun <- bind_rows(inun_1stO, inun_2ndO, inun_3rdO, inun_4thO) %>%
  filter(ti_tot_min > 0 )%>%
  group_by(storm, plan, river)%>%
  summarize(ti_avg_hr = mean(ti_tot_min)/60) %>% 
  mutate(percentRest = case_when(endsWith(plan, "100p")~ 100,
                                 endsWith(plan, "80p")~ 80,
                                 endsWith(plan, "60p")~ 60,
                                 endsWith(plan, "40p")~ 40,
                                 endsWith(plan, "20p")~ 20,
                                 endsWith(plan, "unr")~ 0),
         restLoc = 
           case_when(startsWith(plan, "unr") ~ "unr",
                     startsWith(plan, "1st") ~ "1st",
                     startsWith(plan, "2nd") ~ "2nd",
                     startsWith(plan, "3rd") ~ "3rd",
                     startsWith(plan, "4th") ~ "4th"))

add_Qm <- data.frame(storm = c("Qm", "Qm","Qm", "Qm","Qm", "Qm", "Qm", "Qm","Qm", "Qm","Qm", "Qm","Qm", "Qm", "Qm","Qm"),
                     plan = c("unr","1st-20", "1st-40","unr", "unr","3rd-20","3rd-40","3rd-60","3rd-80","3rd-100","unr", "4th-20","4th-40","4th-60","4th-80","4th-100"),
                     river = c("1-7","1-7","1-7","2-2","3-1", "3-1","3-1","3-1","3-1","3-1","4-1","4-1","4-1","4-1","4-1","4-1"),
                     ti_avg_hr = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
                     percentRest = c(0, 20, 40,0, 0,20, 40, 60, 80, 100, 0,20, 40, 60, 80, 100),
                     restLoc = c("1st","1st", "1st","2nd", "3rd","3rd","3rd","3rd","3rd","3rd", "4th","4th","4th","4th","4th","4th"))
avg_inun <- bind_rows(avg_inun, add_Qm)

avg_inun$storm <- factor(avg_inun$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

avg_inun_1st <- avg_inun%>%
  filter(river == "1-7")%>%
  filter(restLoc == "1st" | restLoc == "unr")%>%
  ggplot()+
  geom_line(aes(percentRest, ti_avg_hr, color = storm, group = storm))+
  geom_point(aes(percentRest, ti_avg_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  xlab(expression(atop("Percent 1"^st*"-order streams restored")))+
  ylab(expression(atop("Average Floodplain Inundation Time (hr)")))+
  ggtitle(expression("1"^st*"-order River"))

avg_inun_2nd <- avg_inun%>%
  filter(river == "2-2")%>%
  filter(restLoc == "2nd" | restLoc == "unr")%>%
  ggplot()+
  geom_line(aes(percentRest, ti_avg_hr, color = storm, group = storm))+
  geom_point(aes(percentRest, ti_avg_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  xlab(expression(atop("Percent 2"^nd*"-order streams restored")))+
  ylab(element_blank())+
  ggtitle(expression("2"^nd*"-order River"))

avg_inun_3rd <- avg_inun%>%
  filter(river == "3-1")%>%
  filter(restLoc == "3rd" | restLoc == "unr")%>%
  ggplot()+
  geom_line(aes(percentRest, ti_avg_hr, color = storm, group = storm))+
  geom_point(aes(percentRest, ti_avg_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  xlab(expression(atop("Percent 3"^rd*"-order streams restored")))+
  ylab(element_blank())+
  ggtitle(expression("3"^rd*"-order River"))

avg_inun_4th <- avg_inun%>%
  filter(river == "4-1")%>%
  filter(restLoc == "4th" | restLoc == "unr")%>%
  ggplot()+
  geom_line(aes(percentRest, ti_avg_hr, color = storm, group = storm))+
  geom_point(aes(percentRest, ti_avg_hr, color = storm))+
  scale_x_continuous(breaks=seq(0,100,by=20))+
  xlab(expression(atop("Percent 4"^th*"-order stream restored")))+
  ylab(element_blank())+
  ggtitle(expression("4"^th*"-order River"))


avg_inun_1st+avg_inun_2nd+avg_inun_3rd+avg_inun_4th +
   plot_layout(ncol = 4, guides = "collect")+
             plot_annotation(title = expression(atop('Average Inundation Time at a Single Cross Section')),
                             tag_levels = 'A',
                             theme = theme(title = element_text(size = 12, face = 2))) &
  theme(text = element_text(size = 10))

ggsave("Figures/avgInun_times.png", dpi=500, height = 4, width = 16,  units="in")
```


##Total inundation time DFs:
```{r}

filter_inun1stO <- inun_1stO %>%
  group_by(storm, plan, river)%>%
  summarize(max_ti_hr = sum(ti_tot_min)/60/24)%>%
  mutate(percentRest = case_when(endsWith(plan, "100p")~ 100,
                                 endsWith(plan, "80p")~ 80,
                                 endsWith(plan, "60p")~ 60,
                                 endsWith(plan, "40p")~ 40,
                                 endsWith(plan, "20p")~ 20,
                                 endsWith(plan, "unr")~ 0))%>%
  mutate(River_Order = 
           case_when(            river == "1-7" ~ "1st", 
                                 river == "2-2" ~ "2nd",
                                 river == "3-1" ~ "3rd",
                                 river == "4-1" ~ "4th")) 
filter_inun1stO$storm <- factor(filter_inun1stO$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

filter_inun2ndO <- inun_2ndO %>%
  group_by(storm, plan, river)%>%
  summarize(max_ti_hr = sum(ti_tot_min)/60/24)%>%
  mutate(percentRest = case_when(endsWith(plan, "100p")~ 100,
                                 endsWith(plan, "80p")~ 80,
                                 endsWith(plan, "60p")~ 60,
                                 endsWith(plan, "40p")~ 40,
                                 endsWith(plan, "20p")~ 20,
                                 endsWith(plan, "unr")~ 0))%>%
  mutate(River_Order = 
           case_when(            river == "1-7" ~ "1st", 
                                 river == "2-2" ~ "2nd",
                                 river == "3-1" ~ "3rd",
                                 river == "4-1" ~ "4th")) 
filter_inun2ndO$storm <- factor(filter_inun2ndO$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

filter_inun3rdO <- inun_3rdO %>%
  group_by(storm, plan, river)%>%
  summarize(max_ti_hr = sum(ti_tot_min)/60/24)%>%
  mutate(percentRest = case_when(endsWith(plan, "100p")~ 100,
                                 endsWith(plan, "80p")~ 80,
                                 endsWith(plan, "60p")~ 60,
                                 endsWith(plan, "40p")~ 40,
                                 endsWith(plan, "20p")~ 20,
                                 endsWith(plan, "unr")~ 0))%>%
  mutate(River_Order = 
           case_when(            river == "1-7" ~ "1st", 
                                 river == "2-2" ~ "2nd",
                                 river == "3-1" ~ "3rd",
                                 river == "4-1" ~ "4th")) 
filter_inun3rdO$storm <- factor(filter_inun3rdO$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

filter_inun4thO <- inun_4thO %>%
  group_by(storm, plan, river)%>%
  summarize(max_ti_hr = sum(ti_tot_min)/60/24)%>%
  mutate(percentRest = case_when(endsWith(plan, "100p")~ 100,
                                 endsWith(plan, "80p")~ 80,
                                 endsWith(plan, "60p")~ 60,
                                 endsWith(plan, "40p")~ 40,
                                 endsWith(plan, "20p")~ 20,
                                 endsWith(plan, "unr")~ 0))%>%
  mutate(River_Order = 
           case_when(            river == "1-7" ~ "1st", 
                                 river == "2-2" ~ "2nd",
                                 river == "3-1" ~ "3rd",
                                 river == "4-1" ~ "4th")) 
filter_inun4thO$storm <- factor(filter_inun4thO$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))
```


#Inundation Profile Graph grid by plan
```{r  plot-wider, fig.width=13, fig.height=4}
inunVSrem1$plan <- factor(inunVSrem1$plan,                 # Re-level group factor
                         levels = c("unr", "1st-20p", "1st-40p","1st-60p", "1st-80p", "1st-100p"))
inunVSrem1$storm <- factor(inunVSrem1$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))
inunVSrem2$plan <- factor(inunVSrem2$plan,                 # Re-level group factor
                         levels = c("unr", "2nd-20p","2nd-60p", "2nd-80p", "2nd-100p"))
inunVSrem2$storm <- factor(inunVSrem2$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))
inunVSrem3$plan <- factor(inunVSrem3$plan,                 # Re-level group factor
                         levels = c("unr", "3rd-20p", "3rd-40p","3rd-60p", "3rd-80p", "3rd-100p"))
inunVSrem3$storm <- factor(inunVSrem3$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))
inunVSrem4$plan <- factor(inunVSrem4$plan,                 # Re-level group factor
                         levels = c("unr", "4th-20p", "4th-40p","4th-60p", "4th-80p", "4th-100p"))
inunVSrem4$storm <- factor(inunVSrem4$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))

inunVSrem1 %>%
  # filter(storm == "Q1") %>%
  filter(river == "1-7" )%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_min, color = storm))+
  facet_wrap( ~ plan, scales = "free", ncol = 3)+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "XS Station (upstream to downstream from left to right)", color = "Storm")+
  ggtitle("Inundation Times Along a 1st-order Reach")
ggsave("Figures/timeProfile17.png", dpi=500, width = 13, height = 4, units="in")
inunVSrem2 %>%
  # filter(storm == "Q1") %>%
  filter(river == "2-2" )%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_min, color = storm))+
  facet_wrap( ~plan, scales = "free", ncol = 3)+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "XS Station (upstream to downstream from left to right)", color = "Storm")+
  ggtitle("Inundation Times Along a 2nd-order Reach")
ggsave("Figures/timeProfile22.png", dpi=500, width = 13, height = 4, units="in")
inunVSrem3 %>%
  # filtr(storm == "Q1") %>%
  filter(river == "3-1" )%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_min, color = storm))+
  facet_wrap( ~plan, scales = "free", ncol = 3)+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "XS Station (upstream to downstream from left to right)", color = "Storm")+
  ggtitle("Inundation Times Along a 3rd-order Reach")
ggsave("Figures/timeProfile31.png", dpi=500, width = 13, height = 4, units="in")
inunVSrem4 %>%
  # filtr(storm == "Q1") %>%
  filter(river == "4-1" )%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_min, color = storm))+
  facet_wrap( ~plan, scales = "free", ncol = 3)+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "XS Station (upstream to downstream from left to right)", color = "Storm")+
  ggtitle("Inundation Times Along the 4th-order Reach")
ggsave("Figures/timeProfile41.png", dpi=500, width = 13, height = 4, units="in")
```

#inundation profiles, single storm 
```{r}

inunVSrem1%>%
  filter(storm == "Q0.5") %>%
  filter(river == "1-7" )%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_min, color = plan))+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "Station (upstream to downstream from left to right)", color = "Q0.5 Restoration \n Plan")+
  ggtitle("Inundation Times Along a 1st-order Reach")

inunVSrem2 %>%
  # filter(storm == "Q0.5") %>%
  filter(river == "2-2" )%>%
  mutate(ti_tot_hr = ti_tot_min/60)%>%
  ggplot()+
  geom_point(aes(STA, ti_tot_hr, color = plan))+
  scale_x_reverse()+
  labs(y = "Total Cross-sectional Inundation Time (min)", x = "Station (upstream to downstream from left to right)", color = "Q0.5 Restoration \n Plan")+
  ggtitle("Inundation Times Along a 2nd-order Reach")

  
```

#Full Restoration
```{r}
#load "Full_InunTimes.Rdata"
# test <- NO3_Full%>%
#   filter(river == "4-1" & storm == "Q0.5" )%>%
#   filter(plan == "3rd-60p"|plan == "3rd-80p"|plan == "3rd-100p")
inunAnT_Full <- NO3_Full %>%
  filter(ti_tot_min > 0)%>%
   mutate(length_ft = 50,
          area_ft2 = case_when(ti_tot_min>0 ~ FP_width*length_ft,
                        TRUE~ 0)) %>%
  # mutate(
  #   k10_removal_g =
  #     case_when(river == "1-7" & STA %in% c(165500,159500)
  #                                   ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000,
  #               river == "1-7" & STA < 165500 & STA > 159500
  #                                   ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
  # 
  #               river == "2-2" & STA %in% c(159500, 154000, 148500, 143000)
  #                                   ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000,
  #               river == "2-2" & (STA < 159500 & STA > 154000) |
  #                                (STA < 154000 & STA > 148500) |
  #                                (STA < 148500 & STA > 143000)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
  # 
  #               river == "3-1" & STA %in% c(143000, 122000, 101000)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000,
  #               river == "3-1" & (STA < 143000 & STA > 122000) |
  #                                (STA < 122000 & STA > 101000)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
  # 
  #               river == "4-1" & (STA < 101000)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k10/1000,
  #               river == "4-1" & STA %in% c(101000, 0)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k10/1000)) %>%
   mutate(
    km_removal_g =
      case_when(river == "1-7" & STA %in% c(165500,159500)
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000,
                river == "1-7" & STA < 165500 & STA > 159500
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "2-2" & STA %in% c(159500, 154000, 148500, 143000)
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000,
                river == "2-2" & (STA < 159500 & STA > 154000) |
                                 (STA < 154000 & STA > 148500) |
                                 (STA < 148500 & STA > 143000)
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "3-1" & STA %in% c(143000, 122000, 101000)
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000,
                river == "3-1" & (STA < 143000 & STA > 122000) |
                                 (STA < 122000 & STA > 101000)
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000,

                river == "4-1" & STA %in% c(101000, 0)
                                      ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*km/1000,
                river == "4-1" & (STA < 101000 & STA > 0)
                                      ~ (ti_tot_min/60)*Xcs*(FP_width*2)*km/1000)) %>%
  # mutate(
  #   k90_removal_g =
  #     case_when(river == "1-7" & STA %in% c(165500,159500)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000,
  #               river == "1-7" & STA < 165500 & STA > 159500
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,
  # 
  #               river == "2-2" & STA %in% c(159500, 154000, 148500, 143000)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000,
  #               river == "2-2" & (STA < 159500 & STA > 154000) |
  #                                (STA < 154000 & STA > 148500) |
  #                                (STA < 148500 & STA > 143000)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,
  # 
  #               river == "3-1" & STA %in% c(143000, 122000, 101000)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000,
  #               river == "3-1" & (STA < 143000 & STA > 122000) |
  #                                (STA < 122000 & STA > 101000)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000,
  # 
  #               river == "4-1" & STA %in% c(101000, 0)
  #                                     ~ (ti_tot_min/60)*(Xcs/2)*(FP_width*2)*k90/1000,
  #               river == "4-1" & (STA < 101000 & STA > 0)
  #                                     ~ (ti_tot_min/60)*Xcs*(FP_width*2)*k90/1000)) %>%
    group_by(storm, plan, river) %>%
    summarise(#removal_k10_g = sum(k10_removal_g),
            removal_km_g = sum(km_removal_g),
            #removal_k90_g = sum(k90_removal_g),
            inun_A = sum(area_ft2, na.rm = TRUE),
            inun_t_avg = mean(ti_tot_min, na.rm = TRUE),
            inun_t_sum = sum(ti_tot_min, na.rm = TRUE))%>% 
    mutate(plan = case_when(startsWith(plan, "full") ~ substring(plan,
                                                               first = 6,
                                                               last = nchar(plan)),
                                                               TRUE ~ plan),
         restLoc = 
           case_when(startsWith(plan, "unr") ~ "1st-order rivers",
                     startsWith(plan, "1st") ~ "1st-order rivers",
                     startsWith(plan, "2nd") ~ "2nd-order rivers",
                     startsWith(plan, "3rd") ~ "3rd-order rivers",
                     startsWith(plan, "4th") ~ "4th-order river"))%>%
  mutate(PerShedRest = case_when(plan == "unr" ~ 0,
                                 plan == "1st-20p" ~ 7, 
                                 plan == "1st-40p" ~ 13,
                                 plan == "1st-60p" ~ 20,
                                 plan == "1st-80p" ~ 27,
                                 plan == "1st-100p" ~ 34,
                                 plan == "2nd-20p" ~ 38,
                                 plan == "2nd-60p" ~ 48,
                                 plan == "2nd-80p" ~ 52,
                                 plan == "2nd-100p" ~ 57,
                                 plan == "3rd-20p" ~ 61,
                                 plan == "3rd-40p" ~ 65,
                                 plan == "3rd-60p" ~ 69,
                                 plan == "3rd-80p" ~ 72,
                                 plan == "3rd-100p" ~ 76,
                                 plan == "4th-20p" ~ 81,
                                 plan == "4th-40p" ~ 86,
                                 plan == "4th-60p" ~ 91,
                                 plan == "4th-80p" ~ 95,
                                 plan == "4th-100p" ~ 100))
add_Qm <- NO3_Full %>%
  group_by(storm, plan, river)%>%
  summarise(ti_tot_min = sum(ti_tot_min),
            FP_width = 0)%>%
  filter(storm == "Qm" )%>%
  filter(ti_tot_min == 0 )%>%
   mutate(length_ft = 50,
          area_ft2 = case_when(ti_tot_min>0 ~ FP_width*length_ft,
                        TRUE~ 0)) %>%
  # mutate(k10_removal_g = 0) %>%
   mutate(
    km_removal_g =0) %>%
  # mutate(
  #   k90_removal_g = 0) %>%
    group_by(storm, plan, river) %>%
    summarise(#removal_k10_g = sum(k10_removal_g),
            removal_km_g = sum(km_removal_g),
            #removal_k90_g = sum(k90_removal_g),
            inun_A = sum(area_ft2, na.rm = TRUE),
            inun_t_avg = mean(ti_tot_min, na.rm = TRUE),
            inun_t_sum = sum(ti_tot_min, na.rm = TRUE))%>% 
    mutate(plan = case_when(startsWith(plan, "full") ~ substring(plan,
                                                               first = 6,
                                                               last = nchar(plan)),
                                                               TRUE ~ plan),
         restLoc = 
           case_when(startsWith(plan, "unr") ~ "1st-order rivers",
                     startsWith(plan, "1st") ~ "1st-order rivers",
                     startsWith(plan, "2nd") ~ "2nd-order rivers",
                     startsWith(plan, "3rd") ~ "3rd-order rivers",
                     startsWith(plan, "4th") ~ "4th-order river"))%>%
  mutate(PerShedRest = case_when(plan == "unr" ~ 0,
                                 plan == "1st-20p" ~ 7, 
                                 plan == "1st-40p" ~ 13,
                                 plan == "1st-60p" ~ 20,
                                 plan == "1st-80p" ~ 27,
                                 plan == "1st-100p" ~ 34,
                                 plan == "2nd-20p" ~ 38,
                                 plan == "2nd-60p" ~ 48,
                                 plan == "2nd-80p" ~ 52,
                                 plan == "2nd-100p" ~ 57,
                                 plan == "3rd-20p" ~ 61,
                                 plan == "3rd-40p" ~ 65,
                                 plan == "3rd-60p" ~ 69,
                                 plan == "3rd-80p" ~ 72,
                                 plan == "3rd-100p" ~ 76,
                                 plan == "4th-20p" ~ 81,
                                 plan == "4th-40p" ~ 86,
                                 plan == "4th-60p" ~ 91,
                                 plan == "4th-80p" ~ 95,
                                 plan == "4th-100p" ~ 100))
add_Q0.5 <- NO3_Full %>%
  group_by(storm, plan, river)%>%
  summarise(ti_tot_min = sum(ti_tot_min),
            FP_width = 0)%>%
  filter(storm == "Q0.5" )%>%
  filter(ti_tot_min == 0 )%>%
   mutate(length_ft = 50,
          area_ft2 = case_when(ti_tot_min>0 ~ FP_width*length_ft,
                        TRUE~ 0)) %>%
  # mutate(k10_removal_g = 0) %>%
   mutate(
    km_removal_g =0) %>%
  # mutate(
  #   k90_removal_g = 0) %>%
    group_by(storm, plan, river) %>%
    summarise(#removal_k10_g = sum(k10_removal_g),
            removal_km_g = sum(km_removal_g),
            #removal_k90_g = sum(k90_removal_g),
            inun_A = sum(area_ft2, na.rm = TRUE),
            inun_t_avg = mean(ti_tot_min, na.rm = TRUE),
            inun_t_sum = sum(ti_tot_min, na.rm = TRUE))%>% 
    mutate(plan = case_when(startsWith(plan, "full") ~ substring(plan,
                                                               first = 6,
                                                               last = nchar(plan)),
                                                               TRUE ~ plan),
         restLoc = 
           case_when(startsWith(plan, "unr") ~ "1st-order rivers",
                     startsWith(plan, "1st") ~ "1st-order rivers",
                     startsWith(plan, "2nd") ~ "2nd-order rivers",
                     startsWith(plan, "3rd") ~ "3rd-order rivers",
                     startsWith(plan, "4th") ~ "4th-order river"))%>%
  mutate(PerShedRest = case_when(plan == "unr" ~ 0,
                                 plan == "1st-20p" ~ 7, 
                                 plan == "1st-40p" ~ 13,
                                 plan == "1st-60p" ~ 20,
                                 plan == "1st-80p" ~ 27,
                                 plan == "1st-100p" ~ 34,
                                 plan == "2nd-20p" ~ 38,
                                 plan == "2nd-60p" ~ 48,
                                 plan == "2nd-80p" ~ 52,
                                 plan == "2nd-100p" ~ 57,
                                 plan == "3rd-20p" ~ 61,
                                 plan == "3rd-40p" ~ 65,
                                 plan == "3rd-60p" ~ 69,
                                 plan == "3rd-80p" ~ 72,
                                 plan == "3rd-100p" ~ 76,
                                 plan == "4th-20p" ~ 81,
                                 plan == "4th-40p" ~ 86,
                                 plan == "4th-60p" ~ 91,
                                 plan == "4th-80p" ~ 95,
                                 plan == "4th-100p" ~ 100))
inunAnT_Full <- bind_rows(inunAnT_Full, add_Qm, add_Q0.5)
inunAnT_Full <- inunAnT_Full%>%
  mutate(inun_t_avgHR =inun_t_avg/60,
         inun_t_sumDAY =inun_t_sum/60/24,
        scale_inunA_m2 = #I scale loads and areas to the watershed here
           case_when(river == "1-7" ~ inun_A*24*0.092903/100000,
                     river == "2-2" ~ inun_A*6*0.092903/100000,
                     river == "3-1" ~ inun_A*2*0.092903/100000,
                     river == "4-1" ~ inun_A*0.092903/100000),
         scaleRemoval_km_kg = 
           case_when(river == "1-7" ~ removal_km_g*24/1000,
                     river == "2-2" ~ removal_km_g*6/1000,
                     river == "3-1" ~ removal_km_g*2/1000,
                     river == "4-1" ~ removal_km_g/1000),
         order = 
           case_when(river == "1-7" ~ "1st-order rivers",
                     river == "2-2" ~ "2nd-order rivers",
                     river == "3-1" ~ "3rd-order rivers",
                     river == "4-1" ~ "4th-order river")) 
# save(inunAnT_Full, Ainun_Full,
#       file = "C:/Users/morganao/Documents/CBT_Oehler2023/12_Saved_Dataframes/Full_inunAnTPlots.RData")

```

#Full Summed and Avg inundation plots
```{r plot-wider, fig.width=17, fig.height=4}
inunAnT_Full$river <- factor(inunAnT_Full$river,                 # Re-level group factor
                         levels = c("1-7", "2-2", "3-1", "4-1"))
inunAnT_Full$storm <- factor(inunAnT_Full$storm,                 # Re-level group factor
                         levels = c("Q2", "Q1", "Q0.5", "Qm"))
inunAnT_Full%>%
ggplot()+
  geom_line(aes(PerShedRest, inun_t_avgHR, color = storm, group = storm))+
  geom_point(aes(PerShedRest, inun_t_avgHR, color = storm, shape = restLoc), size = 1)+
  facet_wrap( ~order, scales = "free", ncol = 4)+
  labs(x = expression(atop("Percent of the 4"^th*"-order Watershed Restored")), 
       y = expression(atop("Average Inundation Time (hrs)")),
       color = "Storm", 
       shape = expression(atop("Location Cumulatively", "Restored Through")))+
  scale_x_continuous(breaks=seq(0,100,by=20),  
                     sec.axis = sec_axis(~.*130.454/100, 
                                         name = "Watershed Length Restored [km]", 
                                         breaks = seq(0,135,10)))+
  ggtitle(expression(atop("Average Inundation Time Due to Full Restoration of the 4"^th*"-order Watershed")))+
  theme(text = element_text(size = 8), 
        title = element_text(size = 10),
        legend.title = element_text(size=8),
        legend.text = element_text(size=6),
        axis.text.x = element_text(size=8))
ggsave("Figures/Full_avgInun_times.png", dpi=500, height = 4, width = 17,  units="in")
```

```{r}
inunAnT_Full %>%
  # filter(plan == "unr")%>%
  # filter(order ==  "1st-order rivers" | order ==  "2nd-order rivers")%>%
  # filter(order ==  "3rd-order rivers" | order ==  "4th-order river")%>%
  ggplot()+
  geom_point(aes(inun_t_sumDAY, scaleRemoval_km_kg, color = storm, shape = order))+
  # xlim(0,20)+
  # ylim(0,30)+
  labs(x = "Summed Inundation time (days)",
       y = expression("NO"[3]*" Load Removed (kg)"),
       color = "Storm", 
       shape = "Inundation Location")+
  ggtitle(expression(atop("Inundation Time vs Nitrate Load Removed Due to Full Restoration (k"[m]*" rate)")))+
  plot_annotation(theme = theme(title = element_text(size = 12, face = 2))) &
  theme(text = element_text(size = 10))

ggsave("Figures/Full_timeSUMvsremoval_km.png", dpi=500, width = 7, height = 4, units="in")
```

